package.json
src/components/MainPage/CardSlider.js
src/components/MainPage/Stars.js
src/styles/star.css

메인페이지 퍼블리싱 : 스타일 수정 

---

src/App.js
src/pages/noticepage/Create.js
src/pages/noticepage/Update.js

[docs]: 페이지 퍼블리싱 완료

---

package-lock.json
src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/DeleteModal.js
src/components/BoothDetail/ImgModal.js
src/index.js

- 사진 모달 세로 중앙 정렬
- 댓글 삭제 함수, 확인 모달 추가
리액트하니까너무행복해요..

fix : 댓글 삭제, 모달 수정

---

package-lock.json
package.json
src/pages/editboothpage/EditBoothPage.js
src/pages/editmenupage/EditMenuDetailPage.js

- 부스 수정 페이지 입력이 안되는 현상 개선
- 메뉴 수정 페이지 input 및 UI 개선

feat : 부스 및 메뉴 페이지 피드백 반영

---

src/App.js
src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/BoothInfo.js
src/components/BoothDetail/BoothMenu.js
src/components/BoothDetail/BoothNotice.js
src/components/BoothDetail/DeleteModal.js
src/pages/boothpage/BoothDetailPage.js

퍼블리싱 피드백 사항 수정 및 코드 정리
질문 사항은 노션에 적어두었습니다

퍼블리싱 피드백 수정

---

src/api/http.js
src/index.js
src/pages/boothpage/Category.js
src/pages/mainpage/MainPage.js
src/pages/reduxTest.js
src/redux/userSlice.js
src/styles/fadeIn.css

로그인 관련 회원 정보 추가 

---

src/App.js
src/components/EditMenu/MenuItem.js
src/pages/boothpage/EditBoothPage.js
src/pages/boothpage/EditMenuDetailPage.js
src/pages/boothpage/EditMenuPage.js

- 경로 변경
- 상태관리 코드 수정
- 그 외 자잘한 css 수정

fix : 경로 변경 및 메뉴 컴포넌트 수정

---

src/pages/boothpage/Category.js
src/pages/mainpage/MainPage.js

fix : 행사 시간, navigate 수정

---

src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/BoothInfo.js
src/components/BoothDetail/BoothNotice.js

소개/공지 개행 해결, 댓글 엔터 막기

---

src/api/booth.js
src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/BoothMenu.js
src/pages/boothpage/BoothDetailPage.js

제목과 같습니다
스크롤 아래로 내리는 것 동기 처리는 아직 못찾았어요..

부스 관리자 댓글 이름 색상 변경 로직 추가

---

src/components/BoothDetail/BoothComments.js

댓글 작성 시 스크롤 아래로 동기 처리

---

src/components/Mypage/MyManager.js
src/components/Mypage/MyUser.js

kmj/ 좋아요한 부스페이지, 상세페이지와 연결

---

src/components/Mypage/MyUser.js

**TF유저 좋아요 누른 부스 상세페이지로 이동안되는 것 수정했습니다.**

kmj/ 유저 좋아요 부스수정

---

src/pages/trashbinpage/TrashPage.js

kmj/ 쓰레기통 애니메이션 수정

---

src/components/NoticePage/CancelButton.js
src/components/NoticePage/UploadButton.js
src/pages/noticepage/Create.js
src/pages/noticepage/Update.js

TF 공지 작성, 수정페이지의 반응형 레이아웃 구현 완료

docs: TF 공지작성, 수정 페이지 css 수정

---

src/components/SideBar.js
src/pages/authpage/RegisterPage.js
src/pages/makerspage/MakersPage.js

만든이들 페이지 오류 수정 
사이드바 스크롤 방지 추가
사이드바 외부 영역 클릭시 바 삭제 기능 추가
회원가입 비밀단어 수정
회원가입 svg 오브젝트로 수정
MakersPage.js 
SideBar.js
RegisterPage.js

만든이들 페이지 수정

---

src/components/Mypage/MyManager.js
src/components/Mypage/MyUser.js
src/pages/trashbinpage/TrashPage.js

**svg object로 변경, 좋아요부스 이미지 삽입 수정** 

kmj/ 쓰레기통 이미지, 좋아요부스 이미지 수정

---

public/index.html
src/AuthRoute.js
src/components/TitleBar.js
src/pages/boothpage/EditBoothPage.js
src/pages/boothpage/EditMenuDetailPage.js
src/pages/boothpage/EditMenuPage.js

타이틀바 css 수정 및 모바일 input 확대 방지

---

src/components/Register/RegisterModal.js
src/pages/authpage/LoginPage.js
src/pages/authpage/RegisterPage.js
src/pages/makerspage/MakersPage.js

회원가입, 로그인 마진 패딩 값 조절
모달 배경 길이 조절, 뒷 배경 스크롤 방지
svg 깨진 파일 방식 수정
LoginPage.js
RegisterPage.js
RegisterModal.js
MakersPage.js

로그인, 회원가입, 만든이들 스타일 수정 

---

package-lock.json
src/api/http.js
src/api/services/tfservice.js
src/api/tf.js
src/pages/noticepage/Create.js
src/pages/noticepage/Update.js

공지 작성, 수정 api 구현 / 아직 미완입니다. 올리면 에러남!

공지 작성 및 수정 api 구현(미완)

---

src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/BoothInfo.js
src/components/BoothDetail/BoothMenu.js
src/components/BoothDetail/BoothNotice.js
src/components/BoothDetail/PartTitle.js
src/pages/boothpage/BoothDetailPage.js

하트 크기 고정, 콘솔 정리

---

src/components/BoothDetail/BoothComments.js
src/components/BoothDetail/BoothMenu.js

메뉴 2줄 이상 오버플로우 수정

---

src/pages/noticepage/NoticeDetailPage.js

Hy/notice fix: 스크롤 오류 반응형 코드 추가

---

src/pages/noticepage/NoticeDetailPage.js
src/pages/noticepage/NoticePage.js

Hy/notice style: 배경색 추가
